### ISSUE TITLE
Returns true but not a valid JSON

### ISSUE THREAD

**Issue by LoicMahieu** [joaquimserafim/is-json#1]
Just found that passing a list as string (`"1,2,3"`) to `isJON()`returns true.
I am trying to look after other cases...

**Comment by joaquimserafim** [comment]
Hi @LoicMahieu, 
:/ , if you find the resolution can send to me a pull request, thanks.

**Comment by joaquimserafim** [comment]
Hi @LoicMahieu, I commit a new version, can you see if fits for you?
thx

**Comment by LoicMahieu** [comment]
Hi @joaquimserafim 
Thanks for commit and sorry for late response, missed the notification.

Unfortunately, `isJSON('[1, 2, 3]')` results false but is valid JSON. (`isJSON.strict('[1, 2, 3]') == true`)
I added test cases and I will take a look ASAP, no time today.

Thanks
