### ISSUE TITLE
wrong logic

### ISSUE THREAD

**Issue by jjeejj** [joaquimserafim/is-json#11]
in you readme file:
```
  var isJSON = require('is-json');

  var good_json = '{"a":"obja","b":[0,1,2],"c":{"d":"some object"}}';
  var bad_json = '{"a":"obja""b":[0,1,2],"c":{"d":"some object"}}';
  var str_number = '121212';


  console.log(isJSON(good_json)); // true
  console.log(isJSON(bad_json)); // false
  console.log(isJSON(str_number)); // false
```

**bad_json shuld return false. but actual return true**

I read index.js file, i found
 `  if (/^\{(.*?)\}$/.test(str))
    return /"(.*?)":(.*?)/g.test(str);`

the logic is wrong, i suggest you relearning the `test` method

**Comment by joaquimserafim** [comment]
@jjeejj thanks mate if you think is there anything wrong just submit a PR please, not gonna get into tech debt mate
