### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by stevenvachon** [joaquimserafim/is-json#14]
I don't get it and am curious about why I'd use this over the `try/catch` approach.

**Comment by joaquimserafim** [comment]
Hi mate you shouldn’t be curious at all With this :) quick answer in the past JS engines like V8 had some perf issues with ops like try/catch and this lib uses part of the algorithm from Crockford to check if is a valid JSON, you don’t need this at all this days, hope this helps you and stay safe!

**Comment by stevenvachon** [comment]
Thank you
