### ISSUE TITLE
The characters `[]` in some string hits a Maximum call stack exeeded

### ISSUE THREAD

**Issue by rodolfoag** [joaquimserafim/is-json#2]
If you call is-json for the string "asdada[]asdadada sd asdasda das das" you'll get the error.

**Comment by joaquimserafim** [comment]
Hey, 

fixed with the version [`2.0.0`](https://github.com/joaquimserafim/is-json/commit/ef8d7aef6b5fcbbff5e11a732040d19caf5f0d00)

thanks
Take care
