### ISSUE TITLE
Is '{"a":}' should be considered as a correct JSON?

### ISSUE THREAD

**Issue by vladholubiev** [joaquimserafim/is-json#6]
Hey! Just curious, is it an intended behaviour? Or this module makes pretty loose assumptions?

![image](https://cloud.githubusercontent.com/assets/3817380/22755723/0e450e98-ee4d-11e6-9223-9433a8d950c3.png)

**Comment by joaquimserafim** [comment]
hey, is not an intended behavior and you are welcomed to improve

Take care
